In [16]:
'''  Question 1: Create an ndarray using the following data. Write the code and outputs.
 Data1 = 1 3 9 12 18, Data2 = 1 5 2 0  ,  Data3 = '7' '6' ,  Data4 = 11 52 20 50
                              3 6 4 7             '5' '4'            34 61 43 17
                                                  '3' '2'

'''

import numpy as np

d1 = [1, 3, 9, 12, 18]
d2 = [[1, 5, 2, 0],[3, 6, 4, 7]]
d3 = [['7', '6'], ['5', '4'], ['3', '2']]
d4 = [[11, 52, 20, 50], [34, 61, 43, 17]]

dataset = [d1, d2, d3, d4]

def create_ndarray(data):
  return np.array(data)
  
arrays = {}
for i, data in enumerate(dataset, start=1):
    arrays[f"arr{i}"] = create_ndarray(data)

arrays


{'arr1': array([ 1,  3,  9, 12, 18]),
 'arr2': array([[1, 5, 2, 0],
        [3, 6, 4, 7]]),
 'arr3': array([['7', '6'],
        ['5', '4'],
        ['3', '2']], dtype='<U1'),
 'arr4': array([[11, 52, 20, 50],
        [34, 61, 43, 17]])}

In [17]:
arrays['arr1']

array([ 1,  3,  9, 12, 18])

In [18]:
''' Question 2: Add Data1 in Data1. Multiply Data1 by 10. Convert Data1, Data2, 
        Data3, and Data4 datatypes to integer. 
                                                ''' 

arrays['arr1'] = arrays['arr1']  + arrays['arr1'] 
arr1 = arrays['arr1']  * 10

def change_to_int(arr):
    return arr.astype(np.int64)

for key in arrays:
    arrays[key] = change_to_int(arrays[key])

arrays


{'arr1': array([ 2,  6, 18, 24, 36], dtype=int64),
 'arr2': array([[1, 5, 2, 0],
        [3, 6, 4, 7]], dtype=int64),
 'arr3': array([[7, 6],
        [5, 4],
        [3, 2]], dtype=int64),
 'arr4': array([[11, 52, 20, 50],
        [34, 61, 43, 17]], dtype=int64)}

In [19]:
''' 
    Question 3: Create:
        A 3x5 array of 0s
        A 2x8 array of 1s
        A 6x3 array of integer random numbers.
'''

def create_nd_zero_array(m, n):
    return np.zeros((m,n))

def create_nd_ones_array(m, n):
    return np.ones((m,n))

def creat_nd_random_array(low, high, m, n):
    return np.random.randint(low, high, (m, n))

zeros = create_nd_zero_array(3, 5)
ones = create_nd_ones_array(2, 8)
ran = creat_nd_random_array(0, 100, 6, 3)

print(f'Zero Array: {zeros}, \n\n Ones Array: {ones}, \n\n Random Array: {ran}')


Zero Array: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], 

 Ones Array: [[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]], 

 Random Array: [[84  3 99]
 [ 1 85 40]
 [81 48  5]
 [51 63 44]
 [42 16 41]
 [36 18 52]]


In [20]:
''' 
    Question 4: Square the bold elements of Data1 and Data2. Hint: Use indexing and slicing.
'''

def square_an_index(arr, ind):
    ''' takes single index as ind=a and for ndarray ind=(a,b) '''
    if ind is not tuple:
        row = ind[0]
        col = ind[1]
        arr[row][col] = arr[row][col] ** 2
        return arr
    else:
        num = arr[ind]
        arr[ind] = num ** 2
        return arr

def square_a_slice(arr, start, end):
    ''' Works for 1D arrays only.
        Squares the elements in the array from index `start` to `end - 1`. '''
    for i in range(start, end):
        arr[i] = arr[i] ** 2
    return arr

# bolds are 9 and 12 in data 1 and 5 and 4 in data 2
print('Data1 with squared bold items:', square_a_slice(arrays['arr1'], 2, 4))
print('-------------------------------')
arrays['arr2'] = square_an_index(arrays['arr2'], (0,1))
print('Data2 with squared bold items:', square_an_index(arrays['arr2'], (1,2)))


Data1 with squared bold items: [  2   6 324 576  36]
-------------------------------
Data2 with squared bold items: [[ 1 25  2  0]
 [ 3  6 16  7]]


In [21]:
''' Question 5: Consider an array Subjects =
                    ML OS CCN
                    OS AI MP
                    CCN ML AI
Set all courses to 0 except ML and AI. Hint: use Boolean indexing.'''


subjects = np.array([['ML', 'OS', 'CCN'], ['OS', 'AI', 'MP'], ['CCN', 'ML', 'AI']])

mask = ~(np.isin(subjects, ['ML', 'AI']))
subjects[mask] = 0
subjects


array([['ML', '0', '0'],
       ['0', 'AI', '0'],
       ['0', 'ML', 'AI']], dtype='<U3')

In [22]:
''' Question 6: Transpose data2 data3 and data4 arrays using appropriate functions '''

arrays['arr2'] = arrays['arr2'].T
arrays['arr3'] = arrays['arr3'].T
arrays['arr4'] = arrays['arr4'].T

arrays


{'arr1': array([  2,   6, 324, 576,  36], dtype=int64),
 'arr2': array([[ 1,  3],
        [25,  6],
        [ 2, 16],
        [ 0,  7]], dtype=int64),
 'arr3': array([[7, 5, 3],
        [6, 4, 2]], dtype=int64),
 'arr4': array([[11, 34],
        [52, 61],
        [20, 43],
        [50, 17]], dtype=int64)}

In [23]:
''' Question 7: Concatenate data2 and data4 using vstack and hstack '''
cat1 = np.vstack((arrays['arr2'], arrays['arr4']))
cat2 = np.hstack((arrays['arr2'], arrays['arr4']))
print("vcat: ", cat1)
print('-------------')
print("hcat: ",cat2)

vcat:  [[ 1  3]
 [25  6]
 [ 2 16]
 [ 0  7]
 [11 34]
 [52 61]
 [20 43]
 [50 17]]
-------------
hcat:  [[ 1  3 11 34]
 [25  6 52 61]
 [ 2 16 20 43]
 [ 0  7 50 17]]


In [24]:
''' Question 8: Demean each column of data2 '''

column_means = np.mean(arrays['arr2'], axis=0)
arrays['arr2'] = arrays['arr2'] - column_means

arrays['arr2']

array([[-6., -5.],
       [18., -2.],
       [-5.,  8.],
       [-7., -1.]])

In [25]:
''' Question 9: Convert Data2 shape into 4x2'''
arrays['arr2'].reshape(4,2)

array([[-6., -5.],
       [18., -2.],
       [-5.,  8.],
       [-7., -1.]])

In [26]:
''' Question 10: Consider the table having marks of three students scored in three subjects. Compute the maximum score of each subject. Hint: use max function.

Subjects	            Student1	Student2	Student3
Subject1 (2 Credit Hour)	60	        70	        50
Subject2 (3 Credit Hour)	40	        60	        80
Subject3 (4 Credit Hour)	70	        55	        65
'''

scores = np.array([
    [60, 70, 50],  
    [40, 60, 80],  
    [70, 55, 65]   
])

credit_hours = np.array([2, 3, 4])  

gps = scores / credit_hours[:, np.newaxis]  # broadcasted division in NumPy

max_adjusted_scores = np.max(gps, axis=1)

subj = ["Subject1", "Subject2", "Subject3"]
for subject, max_score in zip(subj, max_adjusted_scores):
    print(f"The maximum adjusted score in {subj} is {max_score:.2f}.")

The maximum adjusted score in ['Subject1', 'Subject2', 'Subject3'] is 35.00.
The maximum adjusted score in ['Subject1', 'Subject2', 'Subject3'] is 26.67.
The maximum adjusted score in ['Subject1', 'Subject2', 'Subject3'] is 17.50.


In [27]:
''' Question 11: Compute the CGPA for all three students using the given formula:
CGPA = (∑ (Credit hours of a course × Grade point)) / Total credit hours of the courses '''

def get_grade_point(score):
    if 94 <= score <= 100:
        return 4.0
    elif 85 <= score <= 93:
        return 3.7
    elif 80 <= score <= 84:
        return 3.3
    elif 75 <= score <= 79:
        return 3.0
    elif 70 <= score <= 74:
        return 2.7
    elif 65 <= score <= 69:
        return 2.4
    elif 60 <= score <= 64:
        return 2.0
    elif 55 <= score <= 59:
        return 1.7
    elif 50 <= score <= 54:
        return 1.0
    else:
        return 0.0

get_grade_point_vec = np.vectorize(get_grade_point)

grade_points = get_grade_point_vec(scores)

weighted_scores = credit_hours[:, np.newaxis] * grade_points

total_credit_hours = np.sum(credit_hours)
cgpa = np.sum(weighted_scores, axis=0) / total_credit_hours

for i, gpa in enumerate(cgpa, start=1):
    print(f"Student {i} CGPA: {gpa:.2f}")



Student 1 CGPA: 1.64
Student 2 CGPA: 2.02
Student 3 CGPA: 2.39


In [30]:
''' Question 12: Compute the sorted unique values in subjects array '''

unique_sorted_values = np.sort(np.unique(scores))
print("Sorted unique values:", unique_sorted_values)

Sorted unique values: [40 50 55 60 65 70 80]


In [31]:
''' Question 13: Compute the dot product and inverse of 4x4 random matrix using .linalg '''

mat = np.random.rand(4, 4)

dot_product = np.dot(mat, mat.T)
inverse_matrix = np.linalg.inv(mat)

print("Random 4x4 Matrix:")
print(mat)
print("\nDot Product:")
print(dot_product)
print("\nInverse of the Matrix:")
print(inverse_matrix)


Random 4x4 Matrix:
[[0.69911666 0.3736091  0.44710226 0.45994718]
 [0.72219781 0.91890619 0.69380884 0.76192132]
 [0.64977705 0.4079913  0.22734881 0.607589  ]
 [0.8694249  0.38708978 0.73816365 0.31767623]]

Dot Product:
[[1.03979971 1.5088593  0.98780624 1.22859862]
 [1.5088593  2.42785307 1.46484492 1.73778471]
 [0.98780624 1.46484492 1.00951899 1.08369882]
 [1.22859862 1.73778471 1.08369882 1.55154192]]

Inverse of the Matrix:
[[-21.40166146  -0.90739791  12.05707854  10.1022711 ]
 [-32.34432034   2.04630321  15.11538774  13.01203314]
 [ 27.38084822   0.20192113 -15.39817422 -10.67700508]
 [ 34.36123127  -0.47922871 -15.63656165 -15.54606105]]


In [32]:
''' Question 14: Store all created arrays on disk '''
all_arrays = {
    'arr1': arrays['arr1'],
    'arr2': arrays['arr2'],
    'arr3': arrays['arr3'],
    'arr4': arrays['arr4'],
    'scores': scores
}
np.save('all_arrays.npy', all_arrays)

print("Arrays have been saved to disk.")

Arrays have been saved to disk.
