In [53]:
'''  Question 1: Create an ndarray using the following data. Write the code and outputs.
 Data1 = 1 3 9 12 18, Data2 = 1 5 2 0  ,  Data3 = '7' '6' ,  Data4 = 11 52 20 50
                              3 6 4 7             '5' '4'            34 61 43 17
                                                  '3' '2'

'''

import numpy as np

d1 = [1, 3, 9, 12, 18]
d2 = [[1, 5, 2, 0],[3, 6, 4, 7]]
d3 = [['7', '6'], ['5', '4'], ['3', '2']]
d4 = [[11, 52, 20, 50], [34, 61, 43, 17]]

dataset = [d1, d2, d3, d4]

def create_ndarray(data):
  return np.array(data)
  
arrays = {}
for i, data in enumerate(dataset, start=1):
    arrays[f"arr{i}"] = create_ndarray(data)

arrays


{'arr1': array([ 1,  3,  9, 12, 18]),
 'arr2': array([[1, 5, 2, 0],
        [3, 6, 4, 7]]),
 'arr3': array([['7', '6'],
        ['5', '4'],
        ['3', '2']], dtype='<U1'),
 'arr4': array([[11, 52, 20, 50],
        [34, 61, 43, 17]])}

In [54]:
arrays['arr1']

array([ 1,  3,  9, 12, 18])

In [55]:
''' Question 2: Add Data1 in Data1. Multiply Data1 by 10. Convert Data1, Data2, 
        Data3, and Data4 datatypes to integer. 
                                                ''' 

arrays['arr1'] = arrays['arr1']  + arrays['arr1'] 
arr1 = arrays['arr1']  * 10

def change_to_int(arr):
    return arr.astype(np.int64)

for key in arrays:
    arrays[key] = change_to_int(arrays[key])

arrays


{'arr1': array([ 2,  6, 18, 24, 36]),
 'arr2': array([[1, 5, 2, 0],
        [3, 6, 4, 7]]),
 'arr3': array([[7, 6],
        [5, 4],
        [3, 2]]),
 'arr4': array([[11, 52, 20, 50],
        [34, 61, 43, 17]])}

In [56]:
''' 
    Question 3: Create:
        A 3x5 array of 0s
        A 2x8 array of 1s
        A 6x3 array of integer random numbers.
'''

def create_nd_zero_array(m, n):
    return np.zeros((m,n))

def create_nd_ones_array(m, n):
    return np.ones((m,n))

def creat_nd_random_array(low, high, m, n):
    return np.random.randint(low, high, (m, n))

zeros = create_nd_zero_array(3, 5)
ones = create_nd_ones_array(2, 8)
ran = creat_nd_random_array(0, 100, 6, 3)

print(f'Zero Array: {zeros}, \n\n Ones Array: {ones}, \n\n Random Array: {ran}')


Zero Array: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], 

 Ones Array: [[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]], 

 Random Array: [[85  6 41]
 [16  9  1]
 [96 34  6]
 [97 31 23]
 [ 3  3 41]
 [42 61 58]]


In [57]:
''' 
    Question 4: Square the bold elements of Data1 and Data2. Hint: Use indexing and slicing.
'''

def square_an_index(arr, ind):
    ''' takes single index as ind=a and for ndarray ind=(a,b) '''
    if ind is not tuple:
        row = ind[0]
        col = ind[1]
        arr[row][col] = arr[row][col] ** 2
        return arr
    else:
        num = arr[ind]
        arr[ind] = num ** 2
        return arr

def square_a_slice(arr, start, end):
    ''' Works for 1D arrays only.
        Squares the elements in the array from index `start` to `end - 1`. '''
    for i in range(start, end):
        arr[i] = arr[i] ** 2
    return arr

# bolds are 9 and 12 in data 1 and 5 and 4 in data 2
print('Data1 with squared bold items:', square_a_slice(arrays['arr1'], 2, 4))
print('-------------------------------')
arrays['arr2'] = square_an_index(arrays['arr2'], (0,1))
print('Data2 with squared bold items:', square_an_index(arrays['arr2'], (1,2)))


Data1 with squared bold items: [  2   6 324 576  36]
-------------------------------
Data2 with squared bold items: [[ 1 25  2  0]
 [ 3  6 16  7]]
